- name: Ensure sudo group exists
  ansible.builtin.group:
    name: sudo
    state: present

- name: Create ubuntu user
  ansible.builtin.user:
    name: ubuntu
    state: present
    groups: sudo
    shell: /bin/bash
    append: true
    create_home: true

- name: Configure passwordless sudo for sudo group
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Store the first authorized key from root user
  ansible.builtin.command: "head -n 1 /root/.ssh/authorized_keys"
  register: authorized_key
  changed_when: false

- name: Add first authorized key from root to ubuntu user
  ansible.posix.authorized_key:
    user: ubuntu
    state: present
    key: "{{ authorized_key.stdout }}"

- name: Add Deadsnakes PPA for Python 3.12
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install Python 3.12
  ansible.builtin.apt:
    name: ansible
    state: present
    update_cache: true
