- name: Ensure sudo group exists
  ansible.builtin.group:
    name: sudo
    state: present

- name: Create ubuntu user
  ansible.builtin.user:
    name: ubuntu
    state: present
    groups: sudo
    append: true
    create_home: true

- name: Configure passwordless sudo for sudo group
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Store the first authorized key from root user
  ansible.builtin.set_fact:
    authorized_key: "{{ lookup('file', '/root/.ssh/authorized_keys').split('\n') | first }}"

- name: Add first authorized key from root to ubuntu user
  ansible.posix.authorized_key:
    user: ubuntu
    state: present
    key: "{{ authorized_key }}"
