- name: Add Deadsnakes PPA for Python 3.12
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install Python 3.12
  ansible.builtin.apt:
    name:
      - python3.12
      - python3-pip
      - python3.12-venv
    state: present
    update_cache: true

- name: Copy python scripts to remote server
  remote_user: ubuntu
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/ubuntu/wikipedia-mongodb-seeder/
    owner: ubuntu
    mode: "0775"
  with_fileglob:
    - "files/*.py"

- name: Copy requirements to remote server
  remote_user: ubuntu
  ansible.builtin.copy:
    src: files/requirements.txt
    dest: /home/ubuntu/wikipedia-mongodb-seeder/
    owner: ubuntu
    mode: "0775"

- name: Install Python requirements
  remote_user: ubuntu
  ansible.builtin.pip:
    virtualenv: /home/ubuntu/wikipedia-mongodb-seeder/venv
    virtualenv_command: python3.12 -m venv
    requirements: /home/ubuntu/wikipedia-mongodb-seeder/requirements.txt
