- name: Install s3cmd
  ansible.builtin.apt:
    name: s3cmd
    state: present

- name: Encrypt secret
  community.general.systemd_creds_encrypt:
    name: do_access_secret
    pretty: true
    secret: |
      {
          "id": "{{ lookup('ansible.builtin.env', 'DO_SPACES_ACCESS_ID') }}",
          "key": "{{ lookup('ansible.builtin.env', 'DO_SPACES_ACCESS_KEY') }}"
      }
  register: do_access_secret

- name: Copy script to remote server
  ansible.builtin.copy:
    src: files/backup-to-digitalocean-bucket.sh
    dest: /usr/local/bin/mongo-backup/
    owner: ubuntu
    mode: "0700"

- name: Create service unit
  ansible.builtin.template:
    src: templates/mongo-backup.service.j2
    dest: /etc/systemd/system/mongo-backup.service
    owner: root
    group: root
    mode: "0644"
  vars:
    s3_secret: "{{ do_access_secret.value }}"

- name: Create timer unit
  ansible.builtin.copy:
    src: mongo-backup.timer
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: Enable mongo-backup.service
  ansible.builtin.systemd_service:
    name: mongo-backup.service
    enabled: true
    daemon_reload: true
