- name: Add repository key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-8.0.asc
    state: present

- name: Add repository source
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ deb_architecture[ansible_architecture] }}]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }}/mongodb-org/8.0 multiverse
    state: present

- name: Install mongo
  ansible.builtin.apt:
    name: mongodb-org
    update_cache: true
    state: present
