- name: Setup server
  hosts: all
  remote_user: root
  roles:
    - role: base
      tags: [base]
    - role: mongo
      tags: [mongo]
  tasks:
    - name: Copy python scripts to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/ubuntu/
        owner: ubuntu
        mode: "0664"
      with_fileglob:
        - "../wikipedia-mongodb-seeder/*.py"
